from aws_cdk import (
    aws_lambda as _lambda,
    aws_dynamodb as dynamodb,
    Tags,
    Duration,
)
from constructs import Construct
from hackathon_backend.config.environments import Config


class CreateItemLambda(Construct):
    def __init__(self, scope: Construct, construct_id: str, config: Config):
        super().__init__(scope, construct_id)

        self.config = config

        trial_items_table = dynamodb.Table.from_table_name(
            self, "TrialItemsTableRef",
            table_name=self.config.resource_name("Trial_Items"),
        )

        self.function = _lambda.Function(
            self, "CreateItemFunction",
            runtime=_lambda.Runtime.PYTHON_3_11,
            handler="talky_create_item.lambda_handler",
            code=_lambda.Code.from_asset("hackathon_backend/services/lambdas/trial/talky_create_item"),
            # function_name auto-generated by CDK to avoid collisions
            memory_size=self.config.lambda_memory,
            timeout=Duration.seconds(self.config.lambda_timeout_seconds),
            environment={
                "TABLE_NAME": trial_items_table.table_name,
                "ENV": self.config.stage,
                "LOG_LEVEL": self.config.log_level,
            },
        )

        trial_items_table.grant_write_data(self.function)

        for tag_key, tag_value in self.config.get_tags().items():
            Tags.of(self.function).add(tag_key, tag_value)
